const STOCKS = [
  {name:'TCS',symbol:'TCS',sector:'IT',mcap:'14.1L Cr'},
  {name:'Infosys',symbol:'INFY',sector:'IT',mcap:'6.1L Cr'},
  {name:'Wipro',symbol:'WIPRO',sector:'IT',mcap:'2.4L Cr'},
  {name:'HCL Technologies',symbol:'HCLTECH',sector:'IT',mcap:'4.2L Cr'},
  {name:'Tech Mahindra',symbol:'TECHM',sector:'IT',mcap:'1.2L Cr'},
  {name:'LTIMindtree',symbol:'LTIM',sector:'IT',mcap:'1.3L Cr'},
  {name:'Mphasis',symbol:'MPHASIS',sector:'IT',mcap:'0.5L Cr'},
  {name:'Coforge',symbol:'COFORGE',sector:'IT',mcap:'0.4L Cr'},
  {name:'Persistent Systems',symbol:'PERSISTENT',sector:'IT',mcap:'0.7L Cr'},
  {name:'HDFC Bank',symbol:'HDFCBANK',sector:'Banking',mcap:'12.4L Cr'},
  {name:'ICICI Bank',symbol:'ICICIBANK',sector:'Banking',mcap:'7.6L Cr'},
  {name:'SBI',symbol:'SBIN',sector:'Banking',mcap:'6.5L Cr'},
  {name:'Kotak Mahindra Bank',symbol:'KOTAKBANK',sector:'Banking',mcap:'3.5L Cr'},
  {name:'Axis Bank',symbol:'AXISBANK',sector:'Banking',mcap:'3.4L Cr'},
  {name:'IndusInd Bank',symbol:'INDUSINDBK',sector:'Banking',mcap:'1.1L Cr'},
  {name:'Bank of Baroda',symbol:'BANKBARODA',sector:'Banking',mcap:'1.3L Cr'},
  {name:'Punjab National Bank',symbol:'PNB',sector:'Banking',mcap:'1.4L Cr'},
  {name:'Canara Bank',symbol:'CANBK',sector:'Banking',mcap:'1.1L Cr'},
  {name:'Federal Bank',symbol:'FEDERALBNK',sector:'Banking',mcap:'0.4L Cr'},
  {name:'IDFC First Bank',symbol:'IDFCFIRSTB',sector:'Banking',mcap:'0.4L Cr'},
  {name:'Yes Bank',symbol:'YESBANK',sector:'Banking',mcap:'0.4L Cr'},
  {name:'Reliance Industries',symbol:'RELIANCE',sector:'Energy',mcap:'19.2L Cr'},
  {name:'ONGC',symbol:'ONGC',sector:'Energy',mcap:'2.9L Cr'},
  {name:'BPCL',symbol:'BPCL',sector:'Energy',mcap:'1.2L Cr'},
  {name:'IOC',symbol:'IOC',sector:'Energy',mcap:'1.8L Cr'},
  {name:'HPCL',symbol:'HPCL',sector:'Energy',mcap:'0.6L Cr'},
  {name:'Oil India',symbol:'OIL',sector:'Energy',mcap:'0.8L Cr'},
  {name:'Petronet LNG',symbol:'PETRONET',sector:'Energy',mcap:'0.4L Cr'},
  {name:'IGL',symbol:'IGL',sector:'Energy',mcap:'0.3L Cr'},
  {name:'Gujarat Gas',symbol:'GUJGASLTD',sector:'Energy',mcap:'0.3L Cr'},
  {name:'Bharti Airtel',symbol:'BHARTIARTL',sector:'Telecom',mcap:'7.2L Cr'},
  {name:'Vodafone Idea',symbol:'IDEA',sector:'Telecom',mcap:'0.5L Cr'},
  {name:'Tata Communications',symbol:'TATACOMM',sector:'Telecom',mcap:'0.5L Cr'},
  {name:'Maruti Suzuki',symbol:'MARUTI',sector:'Auto',mcap:'3.9L Cr'},
  {name:'Tata Motors',symbol:'TATAMOTORS',sector:'Auto',mcap:'3.6L Cr'},
  {name:'Mahindra & Mahindra',symbol:'M&M',sector:'Auto',mcap:'3.2L Cr'},
  {name:'Hero MotoCorp',symbol:'HEROMOTOCO',sector:'Auto',mcap:'1.0L Cr'},
  {name:'Bajaj Auto',symbol:'BAJAJ-AUTO',sector:'Auto',mcap:'2.3L Cr'},
  {name:'Eicher Motors',symbol:'EICHERMOT',sector:'Auto',mcap:'1.2L Cr'},
  {name:'TVS Motor',symbol:'TVSMOTOR',sector:'Auto',mcap:'1.0L Cr'},
  {name:'Ashok Leyland',symbol:'ASHOKLEY',sector:'Auto',mcap:'0.6L Cr'},
  {name:'MRF',symbol:'MRF',sector:'Auto',mcap:'0.9L Cr'},
  {name:'Apollo Tyres',symbol:'APOLLOTYRE',sector:'Auto',mcap:'0.3L Cr'},
  {name:'Motherson Wiring',symbol:'MOTHERSON',sector:'Auto',mcap:'0.8L Cr'},
  {name:'Bosch',symbol:'BOSCHLTD',sector:'Auto',mcap:'0.9L Cr'},
  {name:'HUL',symbol:'HINDUNILVR',sector:'FMCG',mcap:'5.7L Cr'},
  {name:'ITC',symbol:'ITC',sector:'FMCG',mcap:'5.4L Cr'},
  {name:'Nestle India',symbol:'NESTLEIND',sector:'FMCG',mcap:'2.2L Cr'},
  {name:'Asian Paints',symbol:'ASIANPAINT',sector:'FMCG',mcap:'2.7L Cr'},
  {name:'Britannia',symbol:'BRITANNIA',sector:'FMCG',mcap:'1.2L Cr'},
  {name:'Dabur India',symbol:'DABUR',sector:'FMCG',mcap:'0.9L Cr'},
  {name:'Godrej Consumer',symbol:'GODREJCP',sector:'FMCG',mcap:'1.0L Cr'},
  {name:'Marico',symbol:'MARICO',sector:'FMCG',mcap:'0.7L Cr'},
  {name:'Colgate Palmolive',symbol:'COLPAL',sector:'FMCG',mcap:'0.6L Cr'},
  {name:'Tata Consumer',symbol:'TATACONSUM',sector:'FMCG',mcap:'1.0L Cr'},
  {name:'Varun Beverages',symbol:'VBL',sector:'FMCG',mcap:'1.3L Cr'},
  {name:'Emami',symbol:'EMAMILTD',sector:'FMCG',mcap:'0.2L Cr'},
  {name:'Sun Pharma',symbol:'SUNPHARMA',sector:'Pharma',mcap:'3.7L Cr'},
  {name:'Dr Reddys',symbol:'DRREDDY',sector:'Pharma',mcap:'1.1L Cr'},
  {name:'Cipla',symbol:'CIPLA',sector:'Pharma',mcap:'1.0L Cr'},
  {name:'Divis Labs',symbol:'DIVISLAB',sector:'Pharma',mcap:'1.0L Cr'},
  {name:'Aurobindo Pharma',symbol:'AUROPHARMA',sector:'Pharma',mcap:'0.5L Cr'},
  {name:'Torrent Pharma',symbol:'TORNTPHARM',sector:'Pharma',mcap:'0.8L Cr'},
  {name:'Lupin',symbol:'LUPIN',sector:'Pharma',mcap:'0.6L Cr'},
  {name:'Biocon',symbol:'BIOCON',sector:'Pharma',mcap:'0.3L Cr'},
  {name:'Alkem Labs',symbol:'ALKEM',sector:'Pharma',mcap:'0.4L Cr'},
  {name:'Glenmark Pharma',symbol:'GLENMARK',sector:'Pharma',mcap:'0.2L Cr'},
  {name:'IPCA Labs',symbol:'IPCALAB',sector:'Pharma',mcap:'0.2L Cr'},
  {name:'Abbott India',symbol:'ABBOTINDIA',sector:'Pharma',mcap:'0.3L Cr'},
  {name:'Bajaj Finance',symbol:'BAJFINANCE',sector:'NBFC',mcap:'4.3L Cr'},
  {name:'Bajaj Finserv',symbol:'BAJAJFINSV',sector:'NBFC',mcap:'2.4L Cr'},
  {name:'Cholamandalam Finance',symbol:'CHOLAFIN',sector:'NBFC',mcap:'1.0L Cr'},
  {name:'Muthoot Finance',symbol:'MUTHOOTFIN',sector:'NBFC',mcap:'0.7L Cr'},
  {name:'SBI Cards',symbol:'SBICARD',sector:'NBFC',mcap:'0.5L Cr'},
  {name:'Shriram Finance',symbol:'SHRIRAMFIN',sector:'NBFC',mcap:'1.0L Cr'},
  {name:'L&T Finance',symbol:'LTF',sector:'NBFC',mcap:'0.3L Cr'},
  {name:'HDFC Life',symbol:'HDFCLIFE',sector:'Insurance',mcap:'1.5L Cr'},
  {name:'SBI Life',symbol:'SBILIFE',sector:'Insurance',mcap:'1.5L Cr'},
  {name:'ICICI Prudential',symbol:'ICICIPRULI',sector:'Insurance',mcap:'0.9L Cr'},
  {name:'LIC',symbol:'LICI',sector:'Insurance',mcap:'6.0L Cr'},
  {name:'ICICI Lombard',symbol:'ICICIGI',sector:'Insurance',mcap:'0.9L Cr'},
  {name:'PFC',symbol:'PFC',sector:'Finance',mcap:'1.5L Cr'},
  {name:'REC',symbol:'RECLTD',sector:'Finance',mcap:'1.3L Cr'},
  {name:'IRFC',symbol:'IRFC',sector:'Finance',mcap:'1.9L Cr'},
  {name:'L&T',symbol:'LT',sector:'Infra',mcap:'4.7L Cr'},
  {name:'Adani Ports',symbol:'ADANIPORTS',sector:'Infra',mcap:'2.6L Cr'},
  {name:'Adani Enterprises',symbol:'ADANIENT',sector:'Infra',mcap:'3.5L Cr'},
  {name:'Adani Green',symbol:'ADANIGREEN',sector:'Infra',mcap:'1.8L Cr'},
  {name:'Adani Power',symbol:'ADANIPOWER',sector:'Infra',mcap:'2.2L Cr'},
  {name:'GMR Airports',symbol:'GMRINFRA',sector:'Infra',mcap:'0.7L Cr'},
  {name:'RVNL',symbol:'RVNL',sector:'Infra',mcap:'0.8L Cr'},
  {name:'NCC',symbol:'NCC',sector:'Infra',mcap:'0.2L Cr'},
  {name:'Power Grid',symbol:'POWERGRID',sector:'Utilities',mcap:'2.7L Cr'},
  {name:'NTPC',symbol:'NTPC',sector:'Utilities',mcap:'3.5L Cr'},
  {name:'Tata Power',symbol:'TATAPOWER',sector:'Utilities',mcap:'1.3L Cr'},
  {name:'JSW Energy',symbol:'JSWENERGY',sector:'Utilities',mcap:'0.9L Cr'},
  {name:'Torrent Power',symbol:'TORNTPOWER',sector:'Utilities',mcap:'0.5L Cr'},
  {name:'CESC',symbol:'CESC',sector:'Utilities',mcap:'0.2L Cr'},
  {name:'Tata Steel',symbol:'TATASTEEL',sector:'Metals',mcap:'1.8L Cr'},
  {name:'JSW Steel',symbol:'JSWSTEEL',sector:'Metals',mcap:'2.1L Cr'},
  {name:'Hindalco',symbol:'HINDALCO',sector:'Metals',mcap:'1.4L Cr'},
  {name:'Vedanta',symbol:'VEDL',sector:'Metals',mcap:'1.8L Cr'},
  {name:'Coal India',symbol:'COALINDIA',sector:'Mining',mcap:'2.3L Cr'},
  {name:'NMDC',symbol:'NMDC',sector:'Mining',mcap:'0.5L Cr'},
  {name:'SAIL',symbol:'SAIL',sector:'Metals',mcap:'0.4L Cr'},
  {name:'NALCO',symbol:'NATIONALUM',sector:'Metals',mcap:'0.3L Cr'},
  {name:'Titan',symbol:'TITAN',sector:'Consumer',mcap:'3.0L Cr'},
  {name:'Avenue Supermarts',symbol:'DMART',sector:'Retail',mcap:'2.6L Cr'},
  {name:'Trent',symbol:'TRENT',sector:'Retail',mcap:'1.2L Cr'},
  {name:'Jubilant Foodworks',symbol:'JUBLFOOD',sector:'Consumer',mcap:'0.4L Cr'},
  {name:'Bata India',symbol:'BATAINDIA',sector:'Consumer',mcap:'0.2L Cr'},
  {name:'Kalyan Jewellers',symbol:'KALYANKJIL',sector:'Consumer',mcap:'0.4L Cr'},
  {name:'Vedant Fashions',symbol:'MANYAVAR',sector:'Consumer',mcap:'0.3L Cr'},
  {name:'Apollo Hospitals',symbol:'APOLLOHOSP',sector:'Healthcare',mcap:'0.9L Cr'},
  {name:'Fortis Healthcare',symbol:'FORTIS',sector:'Healthcare',mcap:'0.3L Cr'},
  {name:'Max Healthcare',symbol:'MAXHEALTH',sector:'Healthcare',mcap:'0.7L Cr'},
  {name:'Narayana Health',symbol:'NH',sector:'Healthcare',mcap:'0.2L Cr'},
  {name:'UltraTech Cement',symbol:'ULTRACEMCO',sector:'Cement',mcap:'3.0L Cr'},
  {name:'Shree Cement',symbol:'SHREECEM',sector:'Cement',mcap:'1.0L Cr'},
  {name:'Ambuja Cements',symbol:'AMBUJACEM',sector:'Cement',mcap:'1.0L Cr'},
  {name:'ACC',symbol:'ACC',sector:'Cement',mcap:'0.5L Cr'},
  {name:'Dalmia Bharat',symbol:'DALBHARAT',sector:'Cement',mcap:'0.4L Cr'},
  {name:'JK Cement',symbol:'JKCEMENT',sector:'Cement',mcap:'0.2L Cr'},
  {name:'HAL',symbol:'HAL',sector:'Defence',mcap:'2.3L Cr'},
  {name:'BEL',symbol:'BEL',sector:'Defence',mcap:'1.5L Cr'},
  {name:'BHEL',symbol:'BHEL',sector:'Defence',mcap:'0.8L Cr'},
  {name:'Mazagon Dock',symbol:'MAZDOCK',sector:'Defence',mcap:'0.7L Cr'},
  {name:'Garden Reach',symbol:'GRSE',sector:'Defence',mcap:'0.3L Cr'},
  {name:'Cochin Shipyard',symbol:'COCHINSHIP',sector:'Defence',mcap:'0.3L Cr'},
  {name:'Zomato',symbol:'ZOMATO',sector:'Tech',mcap:'2.1L Cr'},
  {name:'Paytm',symbol:'PAYTM',sector:'Tech',mcap:'0.5L Cr'},
  {name:'Nykaa',symbol:'NYKAA',sector:'Tech',mcap:'0.3L Cr'},
  {name:'PB Fintech',symbol:'POLICYBZR',sector:'Tech',mcap:'0.6L Cr'},
  {name:'IRCTC',symbol:'IRCTC',sector:'Tech',mcap:'0.7L Cr'},
  {name:'MapMyIndia',symbol:'MAPMYINDIA',sector:'Tech',mcap:'0.2L Cr'},
  {name:'Delhivery',symbol:'DELHIVERY',sector:'Logistics',mcap:'0.2L Cr'},
  {name:'Pidilite Industries',symbol:'PIDILITIND',sector:'Chemicals',mcap:'1.4L Cr'},
  {name:'SRF',symbol:'SRF',sector:'Chemicals',mcap:'0.9L Cr'},
  {name:'Deepak Nitrite',symbol:'DEEPAKNTR',sector:'Chemicals',mcap:'0.3L Cr'},
  {name:'Navin Fluorine',symbol:'NAVINFLUOR',sector:'Chemicals',mcap:'0.2L Cr'},
  {name:'Aarti Industries',symbol:'AARTIIND',sector:'Chemicals',mcap:'0.2L Cr'},
  {name:'Tata Chemicals',symbol:'TATACHEM',sector:'Chemicals',mcap:'0.3L Cr'},
  {name:'Vinati Organics',symbol:'VINATIORGA',sector:'Chemicals',mcap:'0.2L Cr'},
  {name:'DLF',symbol:'DLF',sector:'Real Estate',mcap:'1.9L Cr'},
  {name:'Godrej Properties',symbol:'GODREJPROP',sector:'Real Estate',mcap:'0.6L Cr'},
  {name:'Prestige Estates',symbol:'PRESTIGE',sector:'Real Estate',mcap:'0.4L Cr'},
  {name:'Oberoi Realty',symbol:'OBEROIRLTY',sector:'Real Estate',mcap:'0.4L Cr'},
  {name:'Brigade Enterprises',symbol:'BRIGADE',sector:'Real Estate',mcap:'0.2L Cr'},
  {name:'Grasim Industries',symbol:'GRASIM',sector:'Diversified',mcap:'1.5L Cr'},
  {name:'UPL',symbol:'UPL',sector:'Agri',mcap:'0.2L Cr'},
  {name:'PI Industries',symbol:'PIIND',sector:'Agri',mcap:'0.5L Cr'},
  {name:'Coromandel Intl',symbol:'COROMANDEL',sector:'Agri',mcap:'0.3L Cr'},
];
